spring.application.name=vympel
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/vympel_db
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

logging.level.org.hibernate.SQL=warn
logging.level.org.hibernate.type.descriptor.sql=warn

security.jwt.secret=IJBJLHFBVFBV3456789KJVBJ876VFJH(YGV&*2jhVjVUVchevIEf6vcjvyre34r78iuvbkf90wu28hfoorvwuosnkjshf
security.jwt.access-ttl-min=15
security.jwt.refresh-ttl-days=14

